name: Build

on:
  push:
    branches: [ master ]

jobs:

  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install gcc libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

    - name: Build
      run: go build -v .

    - name: Compress
      run: gzip --best --keep boing

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: boing-linux.gz
        path: boing.gz
        
  windows:
    name: Windows Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: boing.exe
        path: boing.exe

  mac:
    name: macOS Build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Compress
      run: gzip --best --keep boing

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: boing-darwin.gz
        path: boing.gz
